#ifndef _GRAMSREADOUT_LIB_H_
#define _GRAMSREADOUT_LIB_H_

/************************************************************************
*  File: gramsreadout_lib.h
*
*  Library for accessing PCI devices, possibly using a Kernel PlugIn driver.
*  The code accesses hardware using WinDriver's WDC library.
*  Code was generated by DriverWizard v16.3.0
*
*  Jungo Connectivity Confidential. Copyright (c) 2024 Jungo Connectivity Ltd.  https://www.jungo.com
*************************************************************************/

#include "wdc_lib.h"
#include "wdc_defs.h"
#include "wdc_diag_lib.h"
#include "pci_regs.h"

// #include "status_strings.h"
#ifdef __cplusplus
extern "C" {
#endif

/*************************************************************
  General definitions
 *************************************************************/
/* Kernel PlugIn driver name (should be no more than 8 characters) */
// Definition moved to CMake file to allow for better portability
// #define KP_GRAMSREADOUT_DRIVER_NAME "KP_PGRAMS"


/* Default vendor and device IDs (0 == all) */
/* TODO: Replace the ID values with your device's vendor and device IDs */
#define GRAMSREADOUT_DEFAULT_VENDOR_ID 0x1172 /* Vendor ID */
#define GRAMSREADOUT_DEFAULT_DEVICE_ID 0x5 /* Device ID */






/* Address space information struct */
#define MAX_TYPE 8
typedef struct {
    DWORD dwAddrSpace;
    CHAR sType[MAX_TYPE];
    CHAR sName[MAX_NAME];
    CHAR sDesc[MAX_DESC];
} GRAMSREADOUT_ADDR_SPACE_INFO;

/* Interrupt result information struct */
typedef struct {
    DWORD dwCounter; /* Number of interrupts received */
    DWORD dwLost;    /* Number of interrupts not yet handled */
    WD_INTERRUPT_WAIT_RESULT waitResult; /* See WD_INTERRUPT_WAIT_RESULT values
                                            in windrvr.h */
    DWORD dwEnabledIntType; /* Interrupt type that was actually enabled
                               (MSI/MSI-X / Level Sensitive / Edge-Triggered) */
    DWORD dwLastMessage; /* Message data of the last received MSI/MSI-X
                            (Windows Vista and higher); N/A to line-based
                            interrupts. */
} GRAMSREADOUT_INT_RESULT;
/* TODO: You can add fields to GRAMSREADOUT_INT_RESULT to store any additional
         information that you wish to pass to your diagnostics interrupt
         handler routine (DiagIntHandler() in gramsreadout_diag.c). */

/* GRAMSREADOUT diagnostics interrupt handler function type */
typedef void (*GRAMSREADOUT_INT_HANDLER)(WDC_DEVICE_HANDLE hDev,
    GRAMSREADOUT_INT_RESULT *pIntResult);

/* GRAMSREADOUT diagnostics plug-and-play and power management events handler function
 * type */
typedef void (*GRAMSREADOUT_EVENT_HANDLER)(WDC_DEVICE_HANDLE hDev, DWORD dwAction);



typedef struct MENU_CTX_DMA {
    WDC_DEVICE_HANDLE *phDev;
    WDC_DEVICE_HANDLE *phDev2;
    DWORD size;
    DWORD dwOptions;
    UINT64 qwAddr;
    PVOID pBuf;
    WD_DMA *pDma;
    DWORD dwDmaAddressWidth;
} MENU_CTX_DMA;

/*************************************************************
  Function prototypes
 *************************************************************/
/* -----------------------------------------------
    GRAMSREADOUT and WDC libraries initialize/uninitialize
   ----------------------------------------------- */
/* Initialize the GRAMSREADOUT and WDC libraries */
DWORD GRAMSREADOUT_LibInit(void);
/* Uninitialize the GRAMSREADOUT and WDC libraries */
DWORD GRAMSREADOUT_LibUninit(void);

#ifndef __KERNEL__
/* -----------------------------------------------
    Device open/close
   ----------------------------------------------- */
/* Open a device handle */
WDC_DEVICE_HANDLE WDC_DIAG_DeviceFindAndOpenSlot(DWORD dwVendorId, DWORD dwDeviceId,
                                                 PCHAR pcKpName, const DWORD dwDevCtxSize, DWORD slotNumber);
WDC_DEVICE_HANDLE GRAMSREADOUT_DeviceOpen(DWORD dwVendorId, DWORD dwDeviceId, DWORD slotNumber);
/* Close a device handle */
BOOL GRAMSREADOUT_DeviceClose(WDC_DEVICE_HANDLE hDev);

#if !defined(ISA) && defined(LINUX)
/* -----------------------------------------------
    SRIOV
   ----------------------------------------------- */
/* Enable SRIOV */
DWORD GRAMSREADOUT_SriovEnable(WDC_DEVICE_HANDLE hDev, DWORD dwNumVFs);
/* Disable SRIOV */
DWORD GRAMSREADOUT_SriovDisable(WDC_DEVICE_HANDLE hDev);
/* Get and store number of virtual functions in *pdwNumVfs */
DWORD GRAMSREADOUT_SriovGetNumVFs(WDC_DEVICE_HANDLE hDev, DWORD *pdwNumVFs);
#endif

/* -----------------------------------------------
    Interrupts
   ----------------------------------------------- */
/* Enable interrupts */
DWORD GRAMSREADOUT_IntEnable(WDC_DEVICE_HANDLE hDev, GRAMSREADOUT_INT_HANDLER funcIntHandler);
/* Disable interrupts */
DWORD GRAMSREADOUT_IntDisable(WDC_DEVICE_HANDLE hDev);
/* Check whether interrupts are enabled for the given device */
BOOL GRAMSREADOUT_IntIsEnabled(WDC_DEVICE_HANDLE hDev);

/* -----------------------------------------------
    Plug-and-play and power management events
   ----------------------------------------------- */
/* Register a plug-and-play or power management event */
DWORD GRAMSREADOUT_EventRegister(WDC_DEVICE_HANDLE hDev,
    GRAMSREADOUT_EVENT_HANDLER funcEventHandler);
/* Unregister a plug-and-play or power management event */
DWORD GRAMSREADOUT_EventUnregister(WDC_DEVICE_HANDLE hDev);
/* Check whether a given plug-and-play or power management event is registered
 */
BOOL GRAMSREADOUT_EventIsRegistered(WDC_DEVICE_HANDLE hDev);

/* -----------------------------------------------
    DMA
   ----------------------------------------------- */
DWORD GRAMSREADOUT_DmaAllocContig(MENU_CTX_DMA *pDmaMenusCtx);
DWORD GRAMSREADOUT_DmaAllocSg(MENU_CTX_DMA *pDmaMenusCtx);
DWORD GRAMSREADOUT_DmaAllocReserved(MENU_CTX_DMA *pDmaMenusCtx);
DWORD GRAMSREADOUT_DmaBufUnlock(WD_DMA *pDma);
#endif /* ifndef __KERNEL */

/* -----------------------------------------------
    Address spaces information
   ----------------------------------------------- */
/* Get number of address spaces */
DWORD GRAMSREADOUT_GetNumAddrSpaces(WDC_DEVICE_HANDLE hDev);
/* Get address space information */
BOOL GRAMSREADOUT_GetAddrSpaceInfo(WDC_DEVICE_HANDLE hDev,
    GRAMSREADOUT_ADDR_SPACE_INFO *pAddrSpaceInfo);




/* -----------------------------------------------
    Debugging and error handling
   ----------------------------------------------- */
/* Get last error */
const char *GRAMSREADOUT_GetLastErr(void);

#ifdef __cplusplus
}
#endif

#endif /* _GRAMSREADOUT_LIB_H_ */

